wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1681000400
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 13
      - 16
      - 19
      4: 3.9.0
      5: 0.12.11
      8:
      - 5
adam:
  desc: null
  value: true
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: models/v5Lite-s.yaml
data:
  desc: null
  value: data/UNIMIB2016.yaml
data_dict:
  desc: null
  value:
    names:
    - bread
    - tangerines
    - carrots
    - schnitzel
    - potatoes/purees
    - yogurt
    - green_beans
    - pudding
    - spinach
    - cutlets
    - pizza
    - pasta_sugar_vegetarian
    - apples
    - pesto_béchamel_pasta_and_croissants
    - lasagna_bolognese
    - moist_courgettes
    - orange
    - pasta_with_fish_sauce
    - chips
    - roast
    - pasta_mussels_and_clams
    - white_rice
    - spinach_and_ricotta_cheese_pie
    - meat_medallions
    - saffron_pasta_and_peas
    - potatoes/pure_ham
    - mixed_salad
    - pasta_mare_e_monti
    - meatballs
    - rustic_savoury_pie_(courgettes)
    - bacon_and_courgette_pasta,
    - ricotta_and_sausage_pasta
    - pizzoccheri
    - fennel_gratin
    - orecchiette_ragu
    - pears
    - tuna_pasta
    - gravy_rice
    - tuna_and_peas_pasta
    - peas
    - savoury_pie_3
    - bananas
    - savoury_pie_(Valle_dAosta_style)
    - salmon_(from_the_menu_it_looks_like_swordfish_actually)
    - calamari_guazzetto
    - fish_2_(fillet)
    - pasta_sauce
    - bruscitt
    - roast_veal
    - pasta_and_beans
    - pork_shank
    - Lombardy_soup
    - stewed_fennel
    - cauliflower
    - white_pasta
    - cod_with_olives
    - breaded_courgettes
    - fish_(fillet)
    - rosbeef
    - cream_cake_2
    - unidentified_white_food
    - roastbeef
    - cream_cake
    - Piedmontese_pastry
    - pasta_and_chickpeas
    - white_focaccia
    - soup
    - cream_soup_of_pumpkin_and_beans
    - chocolate_and_pear_cake
    - pineapple_cake
    - arugula
    - strudel
    nc: 72
    path: ../datasets/UNIMIB2016
    test: test.txt
    train: train.txt
    val: test.txt
device:
  desc: null
  value: '0'
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 100
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.001
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 0.2
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: true
    artifact_alias: latest
    batch_size: 16
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: models/v5Lite-s.yaml
    data: data/UNIMIB2016.yaml
    device: '0'
    entity: null
    epochs: 100
    evolve: false
    exist_ok: false
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.001
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 0.2
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 640
    - 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs/train/exp2
    save_period: -1
    single_cls: false
    sync_bn: false
    total_batch_size: 16
    upload_dataset: false
    weights: pretrained/v5lite-s.pt
    workers: 8
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp2
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 16
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: pretrained/v5lite-s.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
