wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Bounding Box Debugger/Images_wandb_delimeter_predictions:
        key: Bounding Box Debugger/Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': pane
          '1': mandarini
          '10': pizza
          '11': pasta_sugo_vegetariano
          '12': mele
          '13': pasta_pesto_besciamella_e_cornetti
          '14': zucchine_umido
          '15': lasagna_alla_bolognese
          '16': arancia
          '17': pasta_sugo_pesce
          '18': patatine_fritte
          '19': pasta_cozze_e_vongole
          '2': carote
          '20': arrosto
          '21': riso_bianco
          '22': medaglioni_di_carne
          '23': torta_salata_spinaci_e_ricotta
          '24': pasta_zafferano_e_piselli
          '25': patate/pure_prosciutto
          '26': torta_salata_rustica_(zucchine)
          '27': insalata_mista
          '28': pasta_mare_e_monti
          '29': polpette_di_carne
          '3': patate/pure
          '30': pasta_pancetta_e_zucchine
          '31': pasta_ricotta_e_salsiccia
          '32': orecchiette_(ragu)
          '33': pizzoccheri
          '34': finocchi_gratinati
          '35': pere
          '36': pasta_tonno
          '37': riso_sugo
          '38': pasta_tonno_e_piselli
          '39': piselli
          '4': cotoletta
          '40': torta_salata_3
          '41': torta_salata_(alla_valdostana)
          '42': banane
          '43': salmone_(da_menu_sembra_spada_in_realta)
          '44': pesce_2_(filetto)
          '45': bruscitt
          '46': guazzetto_di_calamari
          '47': pasta_e_fagioli
          '48': pasta_sugo
          '49': arrosto_di_vitello
          '5': fagiolini
          '50': stinco_di_maiale
          '51': minestra_lombarda
          '52': finocchi_in_umido
          '53': pasta_bianco
          '54': cavolfiore
          '55': merluzzo_alle_olive
          '56': zucchine_impanate
          '57': pesce_(filetto)
          '58': torta_crema_2
          '59': roastbeef
          '6': yogurt
          '60': rosbeef
          '61': cibo_bianco_non_identificato
          '62': torta_crema
          '63': passato_alla_piemontese
          '64': pasta_e_ceci
          '65': crema_zucca_e_fagioli
          '66': focaccia_bianca
          '67': minestra
          '68': torta_cioccolato_e_pere
          '69': torta_ananas
          '7': budino
          '70': rucola
          '71': strudel
          '8': spinaci
          '9': scaloppine
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1680934395
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 2
      - 13
      - 16
      - 19
      4: 3.9.0
      5: 0.12.11
      8:
      - 5
adam:
  desc: null
  value: true
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: models/v5Lite-s.yaml
data:
  desc: null
  value: data/UNIMIB2016.yaml
data_dict:
  desc: null
  value:
    names:
    - pane
    - mandarini
    - carote
    - patate/pure
    - cotoletta
    - fagiolini
    - yogurt
    - budino
    - spinaci
    - scaloppine
    - pizza
    - pasta_sugo_vegetariano
    - mele
    - pasta_pesto_besciamella_e_cornetti
    - zucchine_umido
    - lasagna_alla_bolognese
    - arancia
    - pasta_sugo_pesce
    - patatine_fritte
    - pasta_cozze_e_vongole
    - arrosto
    - riso_bianco
    - medaglioni_di_carne
    - torta_salata_spinaci_e_ricotta
    - pasta_zafferano_e_piselli
    - patate/pure_prosciutto
    - torta_salata_rustica_(zucchine)
    - insalata_mista
    - pasta_mare_e_monti
    - polpette_di_carne
    - pasta_pancetta_e_zucchine
    - pasta_ricotta_e_salsiccia
    - orecchiette_(ragu)
    - pizzoccheri
    - finocchi_gratinati
    - pere
    - pasta_tonno
    - riso_sugo
    - pasta_tonno_e_piselli
    - piselli
    - torta_salata_3
    - torta_salata_(alla_valdostana)
    - banane
    - salmone_(da_menu_sembra_spada_in_realta)
    - pesce_2_(filetto)
    - bruscitt
    - guazzetto_di_calamari
    - pasta_e_fagioli
    - pasta_sugo
    - arrosto_di_vitello
    - stinco_di_maiale
    - minestra_lombarda
    - finocchi_in_umido
    - pasta_bianco
    - cavolfiore
    - merluzzo_alle_olive
    - zucchine_impanate
    - pesce_(filetto)
    - torta_crema_2
    - roastbeef
    - rosbeef
    - cibo_bianco_non_identificato
    - torta_crema
    - passato_alla_piemontese
    - pasta_e_ceci
    - crema_zucca_e_fagioli
    - focaccia_bianca
    - minestra
    - torta_cioccolato_e_pere
    - torta_ananas
    - rucola
    - strudel
    nc: 72
    path: ../datasets/UNIMIB2016
    test: test.txt
    train: train.txt
    val: test.txt
device:
  desc: null
  value: '0'
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 100
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.001
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 0.2
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: true
    artifact_alias: latest
    batch_size: 16
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: models/v5Lite-s.yaml
    data: data/UNIMIB2016.yaml
    device: '0'
    entity: null
    epochs: 100
    evolve: false
    exist_ok: false
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.001
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 0.2
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 640
    - 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs/train/exp4
    save_period: -1
    single_cls: false
    sync_bn: false
    total_batch_size: 16
    upload_dataset: false
    weights: pretrained/v5lite-s.pt
    workers: 8
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp4
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 16
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: pretrained/v5lite-s.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
